### ISSUE TITLE
Requirements for Milestone 1

### ISSUE THREAD

**Issue by jimmyapodaca** [codesmiths-io/savant-co#1]
Setup application servers and 3rd party application services
-- Github
-- SSL Certificates
-- Filestack and Amazon S3 Storage
-- File hosting
-- Mailgun
Create Back Office & School Models
-- School Profiles
-- Unique School Subdomains
-- SavantCo Back Office Access
Create User Model
-- Account Registration
-- Authorization Permissions
-- Notification System

**Comment by cjeich** [comment]
- [ ] Accounts should have CRUD permissions
- [ ] Just have schools to associate users with
- [ ] Designate user as back office user (can change all schools)
- [ ] Need to mass assign rights to all schools
- [ ] Interface to administrate global accounts
* find all the people with admin permissions
* Filter by schools

- [ ] Interface for Admin at school to administer accounts
- [ ] Update web pack for pipeline
